Document: pa-applet
Title: Debian pa-applet Manual
Author: <insert document author here>
Abstract: This manual describes what pa-applet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pa-applet/pa-applet.sgml.gz

Format: postscript
Files: /usr/share/doc/pa-applet/pa-applet.ps.gz

Format: text
Files: /usr/share/doc/pa-applet/pa-applet.text.gz

Format: HTML
Index: /usr/share/doc/pa-applet/html/index.html
Files: /usr/share/doc/pa-applet/html/*.html
